// <auto-generated />
using System;
using EcommerceSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceSystemDbContext))]
    partial class ECommerceSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cairo",
                            Country = "Egypt",
                            PostalCode = "11765",
                            Street = "Nasr City",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "shipin Elqanter",
                            Country = "Qalyopia",
                            PostalCode = "13713",
                            Street = "Hussin Roshdy",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TotalPrice = 4000m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Not Paid",
                            TotalPrice = 41300m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Not Paid",
                            TotalPrice = 45300m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 45000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            Price = 42000m,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            Price = 42030m,
                            ProductId = 3,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            PaidAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            PaidAt = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Vodafon Cash",
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            PaidAt = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Orange Cash",
                            PaymentStatus = "Completed"
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest Apple iPhone",
                            Name = "iPhone 12",
                            Price = 45000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "55 inch 4K TV",
                            Name = "Samsung Smart TV",
                            Price = 30000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Latest Apple iPhone",
                            Name = "iPhone 14",
                            Price = 45000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "High-performance laptop",
                            Name = "Dell XPS 13",
                            Price = 60000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Noise-cancelling headphones",
                            Name = "Sony WH-1000XM4",
                            Price = 20000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Powerful laptop for professionals",
                            Name = "Apple MacBook Pro",
                            Price = 120000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Google's flagship smartphone",
                            Name = "Google Pixel 6",
                            Price = 40000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Wireless Bluetooth Headphones",
                            Name = "Bose QuietComfort 35 II",
                            Price = 18000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Convertible laptop with touch screen",
                            Name = "HP Spectre x360",
                            Price = 75000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "High-end smartphone with fast performance",
                            Name = "OnePlus 9 Pro",
                            Price = 50000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "65 inch OLED 4K TV",
                            Name = "LG OLED TV",
                            Price = 80000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Gaming laptop with powerful GPU",
                            Name = "Asus ROG Zephyrus G14",
                            Price = 95000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Portable Bluetooth Speaker",
                            Name = "JBL Flip 5",
                            Price = 7000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Sleek laptop with touchscreen",
                            Name = "Microsoft Surface Laptop 4",
                            Price = 85000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Premium smartphone with advanced camera",
                            Name = "Sony Xperia 1 III",
                            Price = 60000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "On-ear noise cancelling headphones",
                            Name = "Beats Solo Pro",
                            Price = 15000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Business laptop with robust features",
                            Name = "Lenovo ThinkPad X1 Carbon",
                            Price = 110000m,
                            Stock = 11
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Cotton T-Shirt",
                            Name = "T-Shirt",
                            Price = 300m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Denim Jeans",
                            Name = "Jeans",
                            Price = 1200m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Running Sneakers",
                            Name = "Sneakers",
                            Price = 2500m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Leather Jacket",
                            Name = "Jacket",
                            Price = 5000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Baseball Cap",
                            Name = "Hat",
                            Price = 800m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Polarized Sunglasses",
                            Name = "Sunglasses",
                            Price = 1500m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Digital Watch",
                            Name = "Watch",
                            Price = 3000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Leather Belt",
                            Name = "Belt",
                            Price = 700m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Wool Scarf",
                            Name = "Scarf",
                            Price = 600m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "Winter Gloves",
                            Name = "Gloves",
                            Price = 400m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Cotton Socks",
                            Name = "Socks",
                            Price = 200m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "Evening Dress",
                            Name = "Dress",
                            Price = 4000m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Denim Skirt",
                            Name = "Skirt",
                            Price = 1500m,
                            Stock = 22
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/images/iphone12-front.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/images/iphone12-back.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/images/samsung-tv.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://example.com/images/iphone14-front.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://example.com/images/iphone14-back.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://example.com/images/dell-xps13.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://example.com/images/sony-headphones.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://example.com/images/apple-watch.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://example.com/images/google-pixel6-front.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://example.com/images/google-pixel6-back.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://example.com/images/lg-refrigerator.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://example.com/images/amazon-echo.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://example.com/images/nintendo-switch.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://example.com/images/fitbit-charge5.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://example.com/images/sony-playstation5.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://example.com/images/microsoft-surface-pro.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://example.com/images/canon-eos-r5.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://example.com/images/bose-quietcomfort35.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://example.com/images/jbl-flip5.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://example.com/images/anker-powercore-10000.jpg",
                            ProductId = 17
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@email.com",
                            Name = "Ahmed Ali",
                            PasswordHash = "hashed123",
                            Phone = "0100000000"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@email.com",
                            Name = "Sara Mohamed",
                            PasswordHash = "hashed456",
                            Phone = "0111111111"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Omar@email.com",
                            Name = "Omar Hassan",
                            PasswordHash = "hashed789",
                            Phone = "0122222222"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila@email.com",
                            Name = "Laila Youssef",
                            PasswordHash = "hashed321",
                            Phone = "0133333333"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahrousellithy99@gmail.com",
                            Name = "mahrous Ellithy",
                            PasswordHash = "mahroushed321",
                            Phone = "01027782815"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "HazemFarag@mail.com",
                            Name = "Hazem Farag",
                            PasswordHash = "hashed654",
                            Phone = "0144444444"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tofaha@gmail.com",
                            Name = "mahmoud tofaha",
                            PasswordHash = "hashed987",
                            Phone = "0155555555"
                        });
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Address", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Order", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceSystem.Domain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Payment", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("EcommerceSystem.Domain.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Product", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("EcommerceSystem.Domain.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceSystem.Domain.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
